# Generated by Django 2.2.2 on 2019-06-24 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0001_initial'),
    ]
   
    operations = [
        migrations.AddField(
            model_name='shoes',
            name='image',
            field=models.ImageField(default=0, upload_to=''),
            preserve_default=False,
        ),
    ]
