# Generated by Django 2.2.2 on 2019-06-24 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0002_shoes_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Electronics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('stock', models.IntegerField()),
                ('Price', models.FloatField()),
                ('image', models.CharField(max_length=2043)),
            ],
        ),
    ]
