# Generated by Django 2.2.2 on 2019-06-26 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flipkart', '0003_electronics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='image',
            field=models.CharField(max_length=2083),
        ),
    ]
